
export const GET_TEMPARATURE_INFO="GET_TEMPARATURE_INFO"
export const GET_WEATHER_INFO="GET_WEATHER_INFO"
export const GET_COORDİNATE_INFO="GET_COORDİNATE_INFO"
export const GET_CİTY_NAME="GET_CİTY_NAME"
export const GET_SYSTEM="GET_SYSTEM"
